# Generated by Django 3.2.5 on 2021-08-17 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('mail_slot_availability', models.BooleanField(null=True)),
                ('slot_booked', models.BooleanField(null=True)),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SlotBookedInfo',
            fields=[
                ('date', models.DateField(max_length=50)),
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_timings', models.CharField(max_length=50)),
                ('center', models.CharField(max_length=50)),
                ('vaccine_type', models.CharField(max_length=50)),
                ('dose', models.IntegerField()),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basic_app.userprofileinfo')),
            ],
        ),
    ]
