# Generated by Django 3.2.5 on 2021-08-23 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbookedinfo',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='slotbookedinfo',
            name='dose',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='pincode',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000, 'Please enter Valid Pincode')]),
        ),
    ]
