# Generated by Django 3.2.5 on 2021-08-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20210823_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotbookedinfo',
            name='dose',
        ),
    ]
