# Generated by Django 3.2.5 on 2021-08-23 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_remove_slotbookedinfo_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbookedinfo',
            name='uid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.userprofileinfo'),
        ),
    ]
