# Generated by Django 3.2.5 on 2021-08-24 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_alter_slotbookedinfo_block_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotbookedinfo',
            name='uid',
        ),
        migrations.AlterField(
            model_name='slotbookedinfo',
            name='block_name',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='slotbookedinfo',
            name='center',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='slotbookedinfo',
            name='date',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='slotbookedinfo',
            name='slot_timings',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='slotbookedinfo',
            name='vaccine_type',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='district',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='password',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='username',
            field=models.CharField(max_length=264),
        ),
        migrations.CreateModel(
            name='BeneficiaryInfo',
            fields=[
                ('name', models.CharField(max_length=264)),
                ('beneficiary_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_booked', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.userprofileinfo')),
            ],
        ),
        migrations.AddField(
            model_name='slotbookedinfo',
            name='beneficiary_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.beneficiaryinfo'),
        ),
    ]
